### ISSUE TITLE
Shock_Response_Spectrum: Reset Button not working

### ISSUE THREAD

**Issue by FrancescaTaddei** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#53]
@rishithellathmeethal The reset button for the two plots on the right does not work.

**Comment by rishithellathmeethal** [comment]
I tried to solve it last week, will make it work this week. 

ValueError: Must stream updates to all existing columns (missing: tmax, extra: omega)

I was getting this error when I tried to clear those plots, I will try and fix it soon

**Comment by FrancescaTaddei** [comment]
@Irfan6220c and @franzi-mittermeier The reset button does not work with the version 1.0.2
@Irfan6220c Please check the comments and change the layout according to the picture below. Thanks
![Unbenannt](https://user-images.githubusercontent.com/25368100/59683559-ab097d00-91d8-11e9-94bf-6b5717678808.JPG)

![Unbenannt2](https://user-images.githubusercontent.com/25368100/59682579-cffcf080-91d6-11e9-83a9-b3e21d6b5580.JPG)

**Comment by m3bert** [comment]
Changed the layout according to the picture
https://github.com/ChairOfStructuralMechanicsTUM/Mechanics_Apps/tree/shock_response_spectra_ME/Shock_Response_Spectra
- no capitals
- no legend
- LaTeX sliders

The "axes" before were actually labels which should belong **inside** the plot. It was just exploiting a bug that allowed to show the labels outside of figures too, which has been fixed in the meantime.

LaTeX for Axis is not supported yet (see [Bokeh Issue](https://github.com/bokeh/bokeh/issues/6031)) and too difficult to implement it as a custom extension like the rest in the /shared folder, since the functions which are used to plot them are all protected in the original Bokeh code. 


_Question/ToDo:_
- [ ] I think the arrow should change its length according to the selected graph and disappear after 1s, correct?
Currently the arrow is always of the same length and displayed during the whole simulation.
